
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: inceptionmachines.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    kind: InceptionMachine
    plural: inceptionmachines
  scope: ""
  validation:
    openAPIV3Schema:
      description: InceptionMachine is the Schema for the inceptionmachines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: InceptionMachineSpec defines the desired state of InceptionMachine
          properties:
            providerID:
              description: 'ProviderID will be the only detail (todo: something else)'
              type: string
          type: object
        status:
          description: InceptionMachineStatus defines the observed state of InceptionMachine
          properties:
            ready:
              description: Ready denotes that the machine is ready
              type: boolean
          required:
          - ready
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
