apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: icluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: InceptionCluster
    name: icluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: InceptionCluster
metadata:
  name: icluster
---
kind: InceptionMachine
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: imachine
spec:
  template:
    spec:
      providerID: iProvider
---
kind: MachineDeployment
apiVersion: cluster.x-k8s.io/v1alpha2
metadata:
  name: ic0
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: icluster
    nodepool: nodepool-0
spec:
  replicas: 5
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: icluster
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: icluster
        nodepool: nodepool-0
    spec:
      version: "v1.15.3"
      bootstrap:
        data: ""  
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: InceptionMachine
        name: imachine
        namespace: default